### ISSUE TITLE
Duplicate Roll Announcement

### ISSUE THREAD

**Issue by DavidDavud** [papa-smurf/Giveitalick-addon#1]
![image](https://user-images.githubusercontent.com/16062575/106156631-115ecb80-6182-11eb-8e6e-9e2e62a604b5.png)

Happens whenever I use the /gl roll feature. Issue persists after reloading & restarting.

**Comment by papa-smurf** [comment]
Hey David! The first message is a "normal" raid message using `/ra` and the other is a raid warning using `/rw`. I haven't had any complaints while using this so far but it's a valid point, I'll change it in the next update thanks for pointing it out :)

**Comment by DavidDavud** [comment]
> Hey David! The first message is a "normal" raid message using `/ra` and the other is a raid warning using `/rw`. I haven't had any complaints while using this so far but it's a valid point, I'll change it in the next update thanks for pointing it out :)

Makes sense, just felt a bit spammy I guess. Other than that the addon seems pretty good so far!

**Comment by papa-smurf** [comment]
Will run with `/rw` only tonight and see how it turns out, keep the feedback coming! ^^

**Comment by DavidDavud** [comment]
On another note, this addon also adds the loot priority thing to tooltips, right? Guessing it's an internal guild thing but with no way to configure/disable it, it might be a bit confusing.

**Comment by papa-smurf** [comment]
100% correct, this is actually something I'm working on as we speak. The item priorities will be detached from the addon and I will make it so that you can import your own from google sheets or a csv format for example :)

**Comment by DavidDavud** [comment]
Recently had another look at the addon because I was trying to figure something out with our ML and was impressed by all the new features. Nice work!

**Comment by papa-smurf** [comment]
Glad you appreciate it! If you or your ML ever have any questions be sure to hook us up on Discord! :)

https://discord.gg/D3mDhYPVzf
